name: Deploy to Hugging Face Spaces

on:
  push:
    branches:
      - main  # Adjust to the branch you are using

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Git LFS
        run: |
          sudo apt-get install git-lfs
          git lfs install

      - name: Configure Git
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git config --global user.email "asroosh@wpi.edu"
          git config --global user.name "Seayar"
          git remote add hf https://huggingface.co/Seayar/Case-study-1
          git fetch hf
          git reset hf/main

      - name: Push Changes to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git add .
          git commit -m "Deploy to Hugging Face Space"
          git push hf HEAD:main
