name: Deploy to Hugging Face Spaces

on:
  push:
    branches:
      - main  # You can change this to the branch you want to use

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Hugging Face Hub
        run: pip install huggingface-hub

      - name: Deploy to Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          huggingface-cli repo create Case-study-1 --space sdk-python --private false
          huggingface-cli repo upload Case-study-1 --include "."
